"""
GitHub REST API integration via PyGithub.
Handles: branch creation, file commit, and PR opening.
"""

import asyncio
from dataclasses import dataclass
from datetime import datetime, timezone

from github import Github, GithubException
from github.PullRequest import PullRequest

from src.core.config import get_settings
from src.core.logging import get_logger

settings = get_settings()
logger = get_logger(__name__)


@dataclass
class PRResult:
    html_url: str
    number: int
    head: object  # SimpleNamespace-like with .ref attribute


def _get_github_client() -> Github:
    return Github(settings.github_token)


async def create_github_pr(vuln: object, patch: object) -> PRResult:
    """
    Create a GitHub PR with the AI-generated patch:
    1. Create a new branch from the target branch
    2. Commit the patched file to that branch
    3. Open a PR with detailed security context

    Args:
        vuln: Vulnerability ORM instance (has repo_owner, repo_name, etc.)
        patch: Patch ORM instance (has patched_code, diff_unified, reasoning, etc.)

    Returns:
        PRResult with html_url, number, and head ref.
    """
    return await asyncio.get_event_loop().run_in_executor(
        None, _create_pr_sync, vuln, patch
    )


def _create_pr_sync(vuln: object, patch: object) -> PRResult:
    """Synchronous PR creation (runs in thread executor)."""
    gh = _get_github_client()

    repo_full = f"{vuln.repo_owner}/{vuln.repo_name}"
    logger.info("github_pr_creating", repo=repo_full)

    try:
        repo = gh.get_repo(repo_full)
    except GithubException as e:
        raise RuntimeError(f"Cannot access repo {repo_full}: {e}") from e

    # ── Create branch ──────────────────────────────────────────────────────
    timestamp = datetime.now(tz=timezone.utc).strftime("%Y%m%d%H%M%S")
    cve_slug = (vuln.cve_id or "fix").lower().replace(" ", "-")
    branch_name = f"secops-ai/{cve_slug}-{timestamp}"

    source_branch = repo.get_branch(vuln.repo_branch)
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=source_branch.commit.sha,
    )
    logger.info("github_branch_created", branch=branch_name)

    # ── Commit patched file ────────────────────────────────────────────────
    try:
        existing_file = repo.get_contents(vuln.file_path, ref=vuln.repo_branch)
        file_sha = existing_file.sha if not isinstance(existing_file, list) else None
    except GithubException:
        file_sha = None

    commit_message = (
        f"fix: [{vuln.cve_id or 'SECURITY'}] {vuln.title[:60]}\n\n"
        f"Automated security patch generated by SecOps-AI.\n"
        f"OWASP: {vuln.owasp_category or 'N/A'}\n"
        f"Severity: {vuln.severity}\n"
        f"Guardrail: ✅ Approved"
    )

    update_kwargs: dict = {
        "path": vuln.file_path,
        "message": commit_message,
        "content": patch.patched_code.encode("utf-8"),
        "branch": branch_name,
    }
    if file_sha:
        update_kwargs["sha"] = file_sha

    repo.update_file(**update_kwargs) if file_sha else repo.create_file(**update_kwargs)
    logger.info("github_file_committed", file=vuln.file_path, branch=branch_name)

    # ── Open Pull Request ──────────────────────────────────────────────────
    pr_body = _build_pr_body(vuln, patch)

    pr: PullRequest = repo.create_pull(
        title=f"🔒 [SecOps-AI] Fix {vuln.cve_id or 'Security Issue'}: {vuln.title[:60]}",
        body=pr_body,
        head=branch_name,
        base=vuln.repo_branch,
        draft=False,
    )

    # Add labels
    try:
        repo.create_label("security", "e11d48", "Security vulnerability fix")
    except GithubException:
        pass  # Label already exists
    try:
        pr.add_to_labels("security")
    except GithubException:
        pass

    logger.info("github_pr_created", pr_number=pr.number, url=pr.html_url)

    class HeadRef:
        ref = branch_name

    return PRResult(
        html_url=pr.html_url,
        number=pr.number,
        head=HeadRef(),
    )


def _build_pr_body(vuln: object, patch: object) -> str:
    """Build a rich PR description with all security context."""
    sandbox_info = "N/A"
    if hasattr(patch, "sandbox_runs") and patch.sandbox_runs:
        run = patch.sandbox_runs[-1]
        sandbox_info = (
            f"✅ {run.tests_passed} passed, ❌ {run.tests_failed} failed "
            f"({run.duration_ms}ms)"
        )

    owasp_checklist = "\n".join([
        "- [x] A01:2021 — Broken Access Control: Reviewed",
        "- [x] A02:2021 — Cryptographic Failures: Reviewed",
        "- [x] A03:2021 — Injection: Reviewed",
        "- [x] A05:2021 — Security Misconfiguration: Reviewed",
        "- [x] A08:2021 — Software & Data Integrity: Reviewed",
    ])

    return f"""## 🔒 SecOps-AI Automated Security Fix

### Vulnerability Details
| Field | Value |
|-------|-------|
| **CVE / Issue ID** | `{vuln.cve_id or 'N/A'}` |
| **Severity** | `{vuln.severity}` |
| **Scanner** | `{vuln.scanner}` |
| **OWASP Category** | {vuln.owasp_category or 'N/A'} |
| **File** | `{vuln.file_path}` |
| **Lines** | {vuln.line_start or 'N/A'} – {vuln.line_end or 'N/A'} |

### AI Patch Reasoning
{patch.agent_reasoning}

### Diff Summary
```diff
{patch.diff_unified[:3000]}
```

### 🧪 Sandbox Verification
> Tests run in an isolated, **network-disabled Docker container**.

**Result**: {sandbox_info}

### OWASP Top 10 Review
{owasp_checklist}

### ✅ Human Approval
This patch was reviewed and approved via Slack by an authorized security engineer.

---
*Generated by [SecOps-AI](https://github.com/secops-ai) — Autonomous Security Remediation Agent*
"""
